### ISSUE TITLE
Sqlite3 not found

### ISSUE THREAD

**Issue by jandolina** [gokayfem/VLM_nodes#132]
These are some amazing nodes. I just did a fresh install of comfy and the vlm nodes on my linux server. When I start comfy I am unable to get the vlm nodes to load. It looks like sqlite3 is missing. Do you know how to fix this?

```
All packages from requirements.txt are installed and up to date.
llama-cpp installed
All packages from requirements.txt are installed and up to date.
Traceback (most recent call last):
  File "/export/home/comfyui/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/export/home/comfyui/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 72, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/export/home/comfyui/custom_nodes/ComfyUI_VLM_nodes/nodes/llavaloader.py", line 4, in <module>
    from llama_cpp import Llama
  File "/export/home/comfyui/venv/lib/python3.10/site-packages/llama_cpp/__init__.py", line 2, in <module>
    from .llama import *
  File "/export/home/comfyui/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 35, in <module>
    from .llama_cache import (
  File "/export/home/comfyui/venv/lib/python3.10/site-packages/llama_cpp/llama_cache.py", line 10, in <module>
    import diskcache
  File "/export/home/comfyui/venv/lib/python3.10/site-packages/diskcache/__init__.py", line 8, in <module>
    from .core import (
  File "/export/home/comfyui/venv/lib/python3.10/site-packages/diskcache/core.py", line 14, in <module>
    import sqlite3
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by gokayfem** [comment]
Fixed. The `sqlite3` dependency came in through `llama-cpp-agent`, which was removed entirely. Nothing in the pack requires it now.
