### ISSUE TITLE
Install issue invalid wheel name...

### ISSUE THREAD

**Issue by Mystic419** [gokayfem/VLM_nodes#134]
After instal and restart I get this...

Attempting to install from https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.5-metal/llama_cpp_python-0.3.5-metal-cp311-cp311-win_amd64.whl
ERROR: llama_cpp_python-0.3.5-metal-cp311-cp311-win_amd64.whl is not a valid wheel filename.

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: F:\My_AI\SDXL\ComfyUI\python_embeded\python.exe -m pip install --upgrade pip
GitHub wheel installation failed: Command '['F:\\My_AI\\SDXL\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.5-metal/llama_cpp_python-0.3.5-metal-cp311-cp311-win_amd64.whl', '--no-cache-dir']' returned non-zero exit status 1.
Attempting source build with acceleration...
Building llama-cpp-python from source with CUDA support
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.3.5.tar.gz (64.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 MB 19.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 231, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 709, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scikit_build_core'

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: F:\My_AI\SDXL\ComfyUI\python_embeded\python.exe -m pip install --upgrade pip
Accelerated build failed: Command '['F:\\My_AI\\SDXL\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python', '--no-cache-dir']' returned non-zero exit status 2.
Falling back to CPU-only version
Installing CPU-only version
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.3.5.tar.gz (64.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 MB 20.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 231, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 709, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scikit_build_core'

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: F:\My_AI\SDXL\ComfyUI\python_embeded\python.exe -m pip install --upgrade pip
CPU installation failed: Command '['F:\\My_AI\\SDXL\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python', '--no-cache-dir']' returned non-zero exit status 2.
Missing or outdated packages: llama-cpp-agent, mkdocs, mkdocs-material, mkdocstrings[python], docstring-parser
Installing/Updating missing packages...
Collecting llama-cpp-agent
  Using cached llama_cpp_agent-0.2.35-py3-none-any.whl.metadata (11 kB)
Collecting mkdocs
  Using cached mkdocs-1.6.1-py3-none-any.whl.metadata (6.0 kB)
Collecting mkdocs-material
  Using cached mkdocs_material-9.5.48-py3-none-any.whl.metadata (18 kB)
Collecting docstring-parser
  Using cached docstring_parser-0.16-py3-none-any.whl.metadata (3.0 kB)
Collecting mkdocstrings[python]
  Using cached mkdocstrings-0.27.0-py3-none-any.whl.metadata (8.1 kB)
Collecting llama-cpp-python>=0.2.60 (from llama-cpp-agent)
  Using cached llama_cpp_python-0.3.5.tar.gz (64.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 231, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 709, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scikit_build_core'

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: F:\My_AI\SDXL\ComfyUI\python_embeded\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "F:\My_AI\SDXL\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\My_AI\SDXL\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 46, in <module>
    check_requirements_installed(llama_cpp_agent_path)
  File "F:\My_AI\SDXL\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 35, in check_requirements_installed
    subprocess.check_call([sys.executable, '-s', '-m', 'pip', 'install', *missing_packages])
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['F:\\My_AI\\SDXL\\ComfyUI\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', 'llama-cpp-agent', 'mkdocs', 'mkdocs-material', 'mkdocstrings[python]', 'docstring-parser']' returned non-zero exit status 2.

Cannot import F:\My_AI\SDXL\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: Command '['F:\\My_AI\\SDXL\\ComfyUI\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', 'llama-cpp-agent', 'mkdocs', 'mkdocs-material', 'mkdocstrings[python]', 'docstring-parser']' returned non-zero exit status 2.

I checked and scikit_build_core is there and I searched google for the file "llama_cpp_python-0.3.5-metal-cp311-cp311-win_amd64.whl" and only found it for "macosx"...  I even tried asking chatGPT, it's helped in the past but not this time...

Thanks for any help...

**Comment by HurrsonBurrson** [comment]
I figured out a workaround. Have not tested much so don't come to me for further support. Disclaimer: I am far from a python expert. 

Find your ComfyUI_VLM_Nodes dir (ie. E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes) and open install_init.py in VS Code or Notepad++.

Find line 158 and comment it out. On line 159, hard code the wheel URL.

Go here, find the version for your system. https://github.com/abetlen/llama-cpp-python/releases/

Right click copy link and paste that link between the quotes on line 159. Save and exit, relaunch CUI.

Good luck.

**Comment by Mystic419** [comment]
I back to the same problem... I am running windows 10 not macosx, there is not a version for windows... I don't believe they are cross compatible or they would have labeled them as such... If I am wrong please correct me. I will wait for a response as I don't know how to remove it if it doesn't work and it breaks something...

**Comment by HurrsonBurrson** [comment]
Use the link in my original comment.

Expand the version you need by clicking assets. cu124 is CUDA 12.4, cu123 is CUDA 12.3 etc....

Find the file matching the version of python you have. ie. llama_cpp_python-0.3.4-cp312-cp312-win_amd64.whl 
cp312 is python 3.12.

**Comment by Mystic419** [comment]
Well it worked... It took me forever to determine what version I needed but the node loaded correctly. Thanks for your help!

**Comment by Mystic419** [comment]
Thanks
