### ISSUE TITLE
Problem loading LLM with LLMLoader

### ISSUE THREAD

**Issue by Kallamamran** [gokayfem/VLM_nodes#135]
File:
```
Q:\ComfyUI\models\LLavacheckpoints\Meta-Llama-3.1-8B-Instruct-Q5_K_S.gguf
```

Error(s):
```
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 292, got 291
llama_load_model_from_file: failed to load model
!!! Exception during processing !!! Failed to load model from file: Q:\ComfyUI\models\LLavacheckpoints\Meta-Llama-3.1-8B-Instruct-Q5_K_S.gguf
Traceback (most recent call last):
  File "Q:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "Q:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "Q:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "Q:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "Q:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\suggest.py", line 292, in load_llm_checkpoint
    llm = Llama(model_path = ckpt_path, chat_format="chatml", offload_kqv=True, f16_kv=True, use_mlock=False, embedding=False, n_batch=1024, last_n_tokens_size=1024, verbose=True, seed=42, n_ctx = max_ctx, n_gpu_layers=gpu_layers, n_threads=n_threads,)
  File "Q:\ComfyUI\venv\lib\site-packages\llama_cpp\llama.py", line 338, in __init__
    self._model = _LlamaModel(
  File "Q:\ComfyUI\venv\lib\site-packages\llama_cpp\_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: Q:\ComfyUI\models\LLavacheckpoints\Meta-Llama-3.1-8B-Instruct-Q5_K_S.gguf
```

**Comment by gokayfem** [comment]
Closing as stale. I could not reproduce this against the current tree, and the code path involved was rewritten between 2.0.0 and 3.3.1 (lazy loading, an owned GPU lifecycle, and a rebuilt llama.cpp runtime). Closing as stale rather than leaving it open indefinitely.

If this still happens on **3.3.1**, please reopen with the new bug report template — it asks for the `VLM Runtime Diagnostics` node output, which captures the environment detail these older reports were missing.
